// app/src/features/sessions/coach-feedback.tsx
import { useState } from 'react';
import { StyleSheet, TextInput, View } from 'react-native';

import { Button, Card, FormError, Text } from '@/components/ui';
import { useCoachActions } from '@/features/coach/queries';
import { formatDayShort, toIsoDay } from '@/lib/format';
import { useTheme } from '@/theme/theme-provider';
import { radius } from '@/theme/tokens';
import { fontFamily } from '@/theme/typography';

type Feedback = { text: string | null; at: string | null } | null | undefined;

type Props = {
  feedback: Feedback;
  /** Renseigné côté coach : lui seul écrit. */
  editable?: { athleteId: string; kind: 'run' | 'strength'; sessionId: string; onSaved: () => void };
};

/**
 * Le retour du coach sur une séance réalisée.
 *
 * Le même bloc des deux côtés : le coach l'écrit et le corrige, l'athlète le
 * lit. Un seul retour par séance — il se modifie, il ne s'empile pas ; une
 * discussion se tient dans la messagerie, pas sous une sortie.
 */
export function CoachFeedbackCard({ feedback, editable }: Props) {
  const { colors } = useTheme();
  const { setSessionFeedback } = useCoachActions();

  const [local, setLocal] = useState<Feedback>(undefined);
  const [editing, setEditing] = useState(false);
  const [draft, setDraft] = useState('');
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const current = (local === undefined ? feedback : local)?.text ?? '';
  const at = (local === undefined ? feedback : local)?.at ?? null;

  if (!editable && !current) return null;

  const save = async () => {
    if (!editable) return;
    setSaving(true);
    setError(null);
    try {
      const saved = await setSessionFeedback(editable.athleteId, editable.kind, editable.sessionId, draft.trim());
      setLocal(saved);
      setEditing(false);
      editable.onSaved();
    } catch (reason) {
      setError(reason instanceof Error ? reason.message : 'Enregistrement impossible.');
    } finally {
      setSaving(false);
    }
  };

  return (
    <Card style={styles.card}>
      <View style={styles.head}>
        <Text variant="sectionTitle" style={styles.flex}>
          {editable ? 'Mon retour' : 'Le retour de ton coach'}
        </Text>
        {at ? <Text variant="caption">{formatDayShort(toIsoDay(new Date(at)))}</Text> : null}
      </View>

      {editing ? (
        <>
          <TextInput
            accessibilityLabel="Retour du coach"
            value={draft}
            onChangeText={setDraft}
            multiline
            maxLength={2000}
            placeholder="Ce que tu as vu de cette séance : ce qui va, ce qu’il faut ajuster la prochaine fois."
            placeholderTextColor={colors.text3}
            style={[styles.input, { backgroundColor: colors.surface, borderColor: colors.borderStrong, color: colors.ink }]}
          />
          <FormError message={error} />
          <View style={styles.actions}>
            <Button label="Annuler" variant="secondary" size="sm" onPress={() => setEditing(false)} style={styles.flex} />
            <Button label={saving ? 'Enregistrement…' : 'Enregistrer'} size="sm" icon="check" disabled={saving} onPress={save} style={styles.flex} />
          </View>
          <Text variant="caption">L’athlète est prévenu à ton premier retour, pas à chaque correction.</Text>
        </>
      ) : current ? (
        <>
          <Text variant="body2" style={[styles.quote, { borderLeftColor: colors.borderStrong }]}>
            « {current} »
          </Text>
          {editable ? (
            <Button
              label="Modifier"
              variant="secondary"
              size="sm"
              icon="pen"
              onPress={() => {
                setDraft(current);
                setEditing(true);
              }}
            />
          ) : null}
        </>
      ) : (
        <>
          <Text variant="body2">Pas encore de retour sur cette séance.</Text>
          <Button
            label="Écrire un retour"
            variant="secondary"
            size="sm"
            icon="pen"
            onPress={() => {
              setDraft('');
              setEditing(true);
            }}
          />
        </>
      )}
    </Card>
  );
}

const styles = StyleSheet.create({
  flex: { flex: 1 },
  card: { gap: 10 },
  head: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  quote: { paddingLeft: 12, borderLeftWidth: 2, fontStyle: 'italic' },
  input: { minHeight: 110, padding: 12, borderWidth: 1, borderRadius: radius.md, fontFamily: fontFamily.regular, fontSize: 14, textAlignVertical: 'top' },
  actions: { flexDirection: 'row', gap: 8 },
});

// web-app/src/app/ui/coach-feedback.component.ts
import { ChangeDetectionStrategy, Component, computed, inject, input, output, signal } from '@angular/core';

import { ApiError } from '../core/api.service';
import { formatDayShort, toIsoDay } from '../core/format';
import { CoachService } from '../data/coach.service';
import { IconComponent } from './icon.component';

/**
 * Le retour du coach sur une séance réalisée.
 *
 * Le même bloc des deux côtés : le coach l'écrit et le corrige, l'athlète le
 * lit. Un seul retour par séance — il se modifie, il ne s'empile pas ; une
 * discussion se tient dans la messagerie, pas sous une sortie.
 */
@Component({
  selector: 'tw-coach-feedback',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [IconComponent],
  template: `
    <section class="card card-pad">
      <div class="spread">
        <span class="h2">{{ editable() ? 'Mon retour' : 'Le retour de ton coach' }}</span>
        @if (savedAt(); as at) {
          <span class="caption muted">{{ dayLabel(at) }}</span>
        }
      </div>

      @if (editable()) {
        @if (editing()) {
          <textarea
            class="input mt"
            rows="4"
            placeholder="Ce que tu as vu de cette séance : ce qui va, ce qu'il faut ajuster la prochaine fois."
            [value]="draft()"
            (input)="draft.set(text($event))"
          ></textarea>
          <div class="row">
            @if (error()) {
              <span class="small err grow">{{ error() }}</span>
            } @else {
              <span class="caption muted-3 grow">L'athlète est prévenu à ton premier retour, pas à chaque correction.</span>
            }
            <button class="btn btn-ghost btn-sm" type="button" (click)="cancel()">Annuler</button>
            <button class="btn btn-primary btn-sm" type="button" [disabled]="saving()" (click)="save()">
              {{ saving() ? 'Enregistrement…' : 'Enregistrer' }}
            </button>
          </div>
        } @else if (current()) {
          <p class="quote">« {{ current() }} »</p>
          <div class="row">
            <span class="grow"></span>
            <button class="btn btn-ghost btn-sm" type="button" (click)="edit()">
              <tw-icon name="edit" [size]="16" [strokeWidth]="2" />
              Modifier
            </button>
          </div>
        } @else {
          <p class="small muted mt-sm">Pas encore de retour sur cette séance.</p>
          <button class="btn btn-ghost btn-sm mt-sm" type="button" (click)="edit()">
            <tw-icon name="edit" [size]="16" [strokeWidth]="2" />
            Écrire un retour
          </button>
        }
      } @else if (current()) {
        <p class="quote">« {{ current() }} »</p>
      } @else {
        <p class="small muted mt-sm">Ton coach n'a pas encore commenté cette séance.</p>
      }
    </section>
  `,
  styles: [
    `
      :host {
        display: block;
      }

      .quote {
        margin: 12px 0 0;
        padding-left: 12px;
        border-left: 2px solid var(--border-strong);
        color: var(--text2);
        font-style: italic;
      }

      .row {
        display: flex;
        align-items: center;
        gap: 8px;
        margin-top: 12px;
      }

      .mt {
        margin-top: 12px;
      }

      .mt-sm {
        margin-top: 8px;
      }

      .err {
        color: var(--danger);
      }
    `,
  ],
})
export class CoachFeedbackComponent {
  private readonly coach = inject(CoachService);

  readonly athleteId = input<string>('');
  readonly kind = input<'run' | 'strength'>('run');
  readonly sessionId = input<string>('');
  readonly feedback = input<{ text: string | null; at: string | null } | null | undefined>(null);
  /** Vrai côté coach : lui seul écrit. */
  readonly editable = input(false);
  readonly saved = output<void>();

  readonly editing = signal(false);
  readonly draft = signal('');
  readonly saving = signal(false);
  readonly error = signal('');
  /** Ce qu'on vient d'enregistrer, tant que l'écran n'a pas rechargé. */
  private readonly local = signal<{ text: string | null; at: string | null } | null>(null);

  readonly current = computed(() => (this.local() ?? this.feedback())?.text ?? '');
  readonly savedAt = computed(() => (this.local() ?? this.feedback())?.at ?? null);

  dayLabel(at: string) {
    return formatDayShort(toIsoDay(new Date(at)));
  }

  edit() {
    this.draft.set(this.current());
    this.error.set('');
    this.editing.set(true);
  }

  cancel() {
    this.editing.set(false);
    this.error.set('');
  }

  save() {
    if (this.saving()) return;
    this.saving.set(true);
    this.error.set('');
    const text = this.draft().trim();
    this.coach.setSessionFeedback(this.athleteId(), this.kind(), this.sessionId(), text).subscribe({
      next: ({ coachFeedback }) => {
        this.saving.set(false);
        this.editing.set(false);
        this.local.set(coachFeedback);
        this.saved.emit();
      },
      error: (err: unknown) => {
        this.saving.set(false);
        this.error.set(err instanceof ApiError ? err.message : 'Enregistrement impossible.');
      },
    });
  }

  text(event: Event) {
    return (event.target as HTMLTextAreaElement).value;
  }
}
